apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: database-snapshot
spec:
  snapshotClassName: csi-snapclass
  source:
    name: database-pvc
    kind: PersistentVolumeClaim
