apiVersion: v1
kind: Service
metadata:
  name: mariadb-test
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb-test
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-test
spec:
  selector:
    matchLabels:
      app: mariadb-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb-test
    spec:
      containers:
      - image: mariadb:10
        name: mariadb-test
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mariadb-test
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
        - name: nfs-persistent-storage
          mountPath: /data
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: database-pvc-clone
      - name: nfs-persistent-storage
        persistentVolumeClaim:
          claimName: nfs-shared
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc-clone
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cvs-extreme
  resources:
    requests:
      storage: 1Ti
  dataSource:
      name: database-snapshot
      kind: VolumeSnapshot
      apiGroup: snapshot.storage.k8s.io
      