kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-shared
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: cvs-premium-extra-protection
