apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: nfs-shared-snap01
spec:
  snapshotClassName: csi-snapclass
  source:
    name: nfs-shared
    kind: PersistentVolumeClaim
