apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: nfs-shared-snap01
spec:
  volumeSnapshotClassName: csi-snapclass
  source:
    persistentVolumeClaimName: nfs-shared
