apiVersion: v1
kind: Pod
metadata:
  name: pvc-helper
spec:
  containers:
  - name: pvc-helper
    image: alpine
    args:
      - sleep
      - "1000000"
    volumeMounts:
      - name: nfs-persistent-storage
        mountPath: /data
  volumes:
    - name: nfs-persistent-storage
      persistentVolumeClaim:
        claimName: nfs-shared
  restartPolicy: Never
